# # Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3'

# Define services
services:

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: ./src 
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on: 
      - redis # This service depends on redis. Start that first.
    ports:
      - "8080:8080"
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  # Redis Service   
  redis:
    image: "redis:6.2-alpine" 
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:    
